### ISSUE TITLE
Add support for Edge Beta

### ISSUE THREAD

**Issue by BalluBisht** [srfrnk/ua-device-detector#16]
Can you please add support for detecting Edge Beta (chromium)

**Comment by srfrnk** [comment]
Sorry for the delay. Can you send me an example of a UA you'd like to have support for?

**Comment by BalluBisht** [comment]
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 Edg/77.0.235.27"

Edge Beta(chromium based) contains `Edg`

**Comment by srfrnk** [comment]
Great thx. So would you think it should be part of the `browser version` or a different `browser` type?

**Comment by BalluBisht** [comment]
You can find more info here

https://social.msdn.microsoft.com/Forums/en-US/edde0150-9478-4ca6-ba0f-9e084b5a4719/how-to-detect-microsoft-edge-chromium-chrome-ie-browser-using-javascript?forum=iewebdevelopment

**Comment by BalluBisht** [comment]
It's a different browser, so I think it should be different browser type.

**Comment by srfrnk** [comment]
I agree. Done.
