### ISSUE TITLE
iOS 13 detection as MacOS

### ISSUE THREAD

**Issue by fadykstas** [srfrnk/ua-device-detector#17]
On iOS 13 window.navigator.userAgent in Safari on iOS 13 is same as on MacOS. Something like this: 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
```
the reason is because "**Request Desktop Website**" parameter is now **enabled by default**, so instead of `os-ios` we get `os-mac` on iOS 13

Indeed, while option change in Settings may be a good solution for the user, any developer can't rely on that. It is as weird as to ask the user to not to use dark mode cause your app doesn't support it instead of opt-out of it using plist. 

Proposal is to add additional validation for `os-mac`:
```
const isIOS = navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1
```
real macs have no multi-touch support, this solution is ideal to detect iOS 13 devices which are the only multi-touch "MacIntel" devices in existence

**Comment by srfrnk** [comment]
Introducing a reference to `navigator` within `parseUserAgent` would break the idempotent design for the module and I would prefer not to do that.

To continue the current design I suggest to add the required information as an option to `parseUserAgent` the same as the user agent is sent.

To keep things as generic as possible I would add two distinct new options:
1) **platform** [optional]: can be initialized from navigator.platform
2) **maxTouchPoints** [optional]: can be initialized from navigator.maxTouchPoints

That would change usage from:
```javascript
var deviceInfo=window.uaDeviceDetector.parseUserAgent({
      userAgent: navigator.userAgent,
});
```
To:
```javascript
var deviceInfo=window.uaDeviceDetector.parseUserAgent({
      userAgent: navigator.userAgent,
      platform: navigator.platform,
      maxTouchPoints: navigator.maxTouchPoints
});
```
Would that be good for you?
