### ISSUE TITLE
Cannot be used with Parcel

### ISSUE THREAD

**Issue by dobesv** [srfrnk/ua-device-detector#5]
Because of the unusual way this thing is packaged into a module, Parcel doesn't recognise the `require` for `re-tree`.

It might be sufficient to not attempt to `require('re-tree')` if `window.reTree` is available.

This might help with the webpack problem as well.

I filed an issue with Parcel, but it can be fixed here as well: https://github.com/parcel-bundler/parcel/issues/1188

**Comment by srfrnk** [comment]
So is that not fixed by [this](https://github.com/srfrnk/ua-device-detector/pull/6)?

**Comment by dobesv** [comment]
In theory that should fix it.  If you release to npm I'll confirm.

**Comment by srfrnk** [comment]
Published to NPM just now. Would be great if you could confirm the fix.

**Comment by dobesv** [comment]
Working for me now.  Thanks for the quick turnaround!
