### ISSUE TITLE
Minified file of the package is out of date

### ISSUE THREAD

**Issue by rybaczewa** [srfrnk/ua-device-detector#8]
Minified file contains code from older version. Including minified file in build produces different results than unminified one.

**Comment by srfrnk** [comment]
Thanx. Published a new version with latest JS minified.
Please confirm.

**Comment by rybaczewa** [comment]
Using minified version:
```
> uaDeviceDetector.parseUserAgent('Mozilla/5.0 (Linux; Android 4.4; Nexus 7 Build/KOT24) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.105 Safari/537.36').os_version
"4.4"
```
All good, thanks for fast response.

**Comment by srfrnk** [comment]
gr8 😁 can we close this issue then?

**Comment by rybaczewa** [comment]
Sure, closing!
